## Configuration file for the run

RUN_NAME: V1_neuronal_selection # MUST be set. Creates a subfolder in the runs folder with this name, containing data, saved models, etc. IMPORTANT: all values in this folder WILL be deleted.
ASK_FOR_CONFIRMATION: False # If True, will ask for user configuration before running preprocessing, training, etc. If False, will ust continue (useful for overnight runs)

# Data parameters

data:
  DATA_NAME: V1_neuronal_selection # the name of the folder where to get the data from. May be different from RUN_NAME if reusing data between runs
  keep_behavioral_info: False
  area_of_interest: 'V1' # None for all neurons, 'PM' for only PM neurons, 'V1' for only V1 neurons
  sessions_to_keep: 'all' # 'all' or list of sessions to keep, eg [['LPE10885', '2023_10_20'], ...]
  OUTPUT_NAME: 'V1_neuronal_selection' # Name of the output folder in data/ where the data will be saved.
  INPUT_FOLDER: '../sensorium/notebooks/data/IM_prezipped' # relative to molanalysis root folder (can change data locations)

MEIs:
  # data_key: 'LPE10885-LPE10885_2023_10_20-0' # format: session_id-session_id_date[YYYY_MM_DD]-0
  session_id: 'LPE10885'
  session_date: '2023_10_20' # format: YYYY_MM_DD
  tier: 'test' # 'test', 'train', 'validation', or 'final_test'. Which tier of the data to select the neurons for MEI generation. TODO: Implement 'all'
  also_output_to_local: False
  local_output_folder: 'T:/Bonsai/lab-leopoldo-solene-vr/workflows/MEIs/'
  shape: [68, 135] # shape of the MEI. Needs to be a list of two integers.